from fpdf import FPDF
import datetime
import os

class FarmingReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_fill_color(34, 139, 34)
        self.set_text_color(255, 255, 255)
        self.cell(0, 12, '  Smart Farming AI - Disease Diagnosis Report', fill=True, ln=True)
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by Smart Farming AI | Page {self.page_no()}', align='C')

def generate_report(
    disease: str,
    confidence: float,
    severity: dict,
    treatment: str,
    top3: list,
    image_path: str = None
) -> bytes:

    pdf = FarmingReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Date and time
    now = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")
    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 6, f'Report generated: {now}', ln=True)
    pdf.ln(4)

    # Disease name
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(34, 139, 34)
    pdf.cell(0, 8, 'Diagnosis Summary', ln=True)
    pdf.ln(2)

    # Results table
    pdf.set_font('Helvetica', '', 11)
    pdf.set_text_color(0, 0, 0)

    disease_clean = disease.replace("___", " - ").replace("_", " ")
    severity_label = severity.get("label", "Unknown")
    severity_pct   = severity.get("percentage", 0)

    rows = [
        ("Detected Disease", disease_clean),
        ("Confidence Score", f"{confidence * 100:.1f}%"),
        ("Severity Level",   f"{severity_label} ({severity_pct}% infected area)"),
        ("Diagnosis Date",   now),
    ]

    for label, value in rows:
        pdf.set_fill_color(240, 248, 240)
        pdf.set_font('Helvetica', 'B', 10)
        pdf.cell(60, 8, label, border=1, fill=True)
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(0, 8, value, border=1, ln=True)

    pdf.ln(6)

    # Top 3 predictions
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(34, 139, 34)
    pdf.cell(0, 8, 'Top 3 Predictions', ln=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_fill_color(34, 139, 34)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(10, 8, '#', border=1, fill=True)
    pdf.cell(120, 8, 'Disease', border=1, fill=True)
    pdf.cell(0, 8, 'Confidence', border=1, fill=True, ln=True)

    pdf.set_text_color(0, 0, 0)
    for i, pred in enumerate(top3):
        pdf.set_fill_color(240, 248, 240) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.set_font('Helvetica', '', 10)
        pname = pred["disease"].replace("___", " - ").replace("_", " ")
        pconf = f"{pred['confidence'] * 100:.1f}%"
        pdf.cell(10, 8, str(i+1), border=1, fill=True)
        pdf.cell(120, 8, pname, border=1, fill=True)
        pdf.cell(0, 8, pconf, border=1, fill=True, ln=True)

    pdf.ln(6)

    # Treatment plan
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(34, 139, 34)
    pdf.cell(0, 8, 'Treatment Plan', ln=True)
    pdf.ln(2)

    pdf.set_font('Helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)

    # Clean treatment text
    treatment_clean = treatment.replace('**', '').replace('##', '').replace('#', '')
    for line in treatment_clean.split('\n'):
        line = line.strip()
        if line:
            pdf.multi_cell(0, 6, line)
            pdf.ln(1)

    pdf.ln(4)

    # Severity guide
    pdf.set_font('Helvetica', 'B', 14)
    pdf.set_text_color(34, 139, 34)
    pdf.cell(0, 8, 'Severity Guide', ln=True)
    pdf.ln(2)

    severity_guide = [
        ("Mild (< 20%)",        "Preventive spray, monitor weekly"),
        ("Moderate (20-50%)",   "Targeted fungicide, remove affected leaves"),
        ("Severe (> 50%)",      "Immediate treatment, possible quarantine"),
    ]

    for level, action in severity_guide:
        pdf.set_font('Helvetica', 'B', 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(60, 7, level, border=1)
        pdf.set_font('Helvetica', '', 10)
        pdf.cell(0, 7, action, border=1, ln=True)

    pdf.ln(6)

    # Footer note
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 5,
        'Note: This report is generated by AI and should be verified by an agricultural expert. '
        'Treatment recommendations are based on general guidelines and may vary by region and conditions.'
    )

    return bytes(pdf.output())